### PR TITLE
fix(604): don't treat disconnected as terminal

### LINKED ISSUE #604: [Bug]: Voice transport 'disconnected' is treated as terminal and causes premature teardown
While testing for #552 I noticed that Sharkord currently treats mediasoup/WebRTC transport state 'disconnected' as a hard failure. This is incorrect (at least from testing and documentation): under temporary network degradation the transport often recovers to 'connected' on its own. Because of this, Sharkord tears down voice sessions prematurely instead of allowing transient disconnects to recover.

See https://developer.mozilla.org/en-US/docs/Web/API/RTCPeerConnection/connectionState.

## Sample Logs of the fix
I have a fixed version running already and you can see, when forcing bad internet via  `tc` dropping packages, introducing latency etc, it can easily recover:

```
16:57:54.549 [VOICE-PROVIDER] Producer transport connection state changed 
Object { state: "connected" }
index-B03MkC9W.js:59:41994
16:57:56.872 [VOICE-PROVIDER] Transport state change 
Object { transport: "consumer", state: "disconnected" }
index-B03MkC9W.js:59:41994
16:57:56.872 [VOICE-PROVIDER] Consumer transport connection state changed 
Object { state: "disconnected" }
index-B03MkC9W.js:59:41994
16:57:57.255 [VOICE-PROVIDER] Transport state change 
Object { transport: "consumer", state: "connected" }
index-B03MkC9W.js:59:41994
16:57:57.255 [VOICE-PROVIDER] Consumer transport connection state changed 
Object { state: "connected" }
index-B03MkC9W.js:59:41994
16:58:09.900 [VOICE-PROVIDER] Transport state change 
Object { transport: "producer", state: "disconnected" }
index-B03MkC9W.js:59:41994
16:58:09.900 [VOICE-PROVIDER] Producer transport connection state changed 
Object { state: "disconnected" }
index-B03MkC9W.js:59:41994
16:58:10.297 [VOICE-PROVIDER] Transport state change 
Object { transport: "producer", state: "connected" }
index-B03MkC9W.js:59:41994
16:58:10.298 [VOICE-PROVIDER] Producer transport connection state changed 
Object { state: "connected" }
index-B03MkC9W.js:59:41994
16:58:41.572 [VOICE-PROVIDER] Transport state change 
Object { transport: "consumer", state: "disconnected" }
index-B03MkC9W.js:59:41994
16:58:41.572 [VOICE-PROVIDER] Consumer transport connection state changed 
Object { state: "disconnected" }
index-B03MkC9W.js:59:41994
16:58:46.688 [VOICE-PROVIDER] Transport state change 
Object { transport: "producer", state: "disconnected" }
index-B03MkC9W.js:59:41994
16:58:46.689 [VOICE-PROVIDER] Producer transport connection state changed 
Object { state: "disconnected" }
index-B03MkC9W.js:59:41994
16:58:46.756 [VOICE-PROVIDER] Transport state change 
Object { transport: "consumer", state: "connected" }
index-B03MkC9W.js:59:41994
16:58:46.756 [VOICE-PROVIDER] Consumer transport connection state changed 
Object { state: "connected" }
```

### PR DESCRIPTION
**Pull request by schemen**
## Summary

Sharkord currently treats mediasoup/WebRTC transport state 'disconnected' as a hard failure. This is incorrect: under temporary network degradation the transport often recovers to 'connected' on its own. Because of this, Sharkord tears down voice sessions prematurely instead of allowing transient disconnects to recover.

Closes #604 

## Additional Context

This is from testing for #552 - I removed all the reconnect stuff and reduced the change to only dealing with the mediasoup transport state. Testing with `tc` as well as a full game session with a friend with bad internet seemed to show that all `disconnected` states were recoverable.

Additionally, there is a tiny helper that shows a reason when using leaveVoice()

### CODE REVIEW

File: apps/client/src/components/channel-view/voice/controls-bar.tsx [hunk 1]
```diff
@@ -95,7 +95,7 @@ const ControlsBar = memo(({ channelId }: TControlsBarProps) => {
             'pointer-events-auto h-14 w-18 rounded-md text-white shadow-xl transition-all active:scale-95',
             'bg-[#ec4245] hover:bg-[#da373c]'
           )}
-          onClick={leaveVoice}
+          onClick={() => void leaveVoice()}
```
Comment (diogomartino) [inline apps/client/src/components/channel-view/voice/controls-bar.tsx]: Not necessary

File: apps/client/src/components/left-sidebar/voice-control.tsx [hunk 2]
```diff
@@ -83,7 +83,13 @@ const VoiceControl = memo(() => {
         </StatsPopover>
 
         <div className="flex items-center justify-between px-2 py-2">
-          <Button variant="outline" size="sm" onClick={leaveVoice}>
+          <Button
+            variant="outline"
+            size="sm"
+            onClick={() =>
+              void leaveVoice({ reason: 'user_disconnect_button' })
```
Comment (diogomartino) [inline apps/client/src/components/left-sidebar/voice-control.tsx]: Remove the void, not necessary.

**Review by diogomartino — CHANGES_REQUESTED** [review]
Just remove the voids that I don't like and it's good to go.

**Comment by schemen** [comment]
Updated as requested :-) Ready to be reviewed

**Review by diogomartino — APPROVED** [review]
Ty!

**Comment by LykanMonolyth** [comment]
Thanks so much for this @schemen!  Looking forward to this getting into an upcoming release. 

#552 which released with 0.0.16 definitely made the situation worse if someone's connection goes sour. It got so bad for one of my users, I had to push us back to 0.0.15 to ensure better stability overall for everyone.

**Comment by schemen** [comment]
> Thanks so much for this @schemen! Looking forward to this getting into an upcoming release.
> 
> #552 which released with 0.0.16 definitely made the situation worse if someone's connection goes sour. It got so bad for one of my users, I had to push us back to 0.0.15 to ensure better stability overall for everyone.

This was part of the 0.0.16 release. Do you or your users have any logs of what appears to be happening? See #604 as example.

**Comment by LykanMonolyth** [comment]
> > Thanks so much for this @schemen! Looking forward to this getting into an upcoming release.
> > #552 which released with 0.0.16 definitely made the situation worse if someone's connection goes sour. It got so bad for one of my users, I had to push us back to 0.0.15 to ensure better stability overall for everyone.
> 
> This was part of the 0.0.16 release. Do you or your users have any logs of what appears to be happening? See #604 as example.

@schemen 
I had to bump us back up to 0.0.16 this afternoon but even just a couple hours after the upgrade he had issues where he stops being able to hear us but we can still hear him. He did not have these issues prior to 0.0.16. He is running Brave (as are the rest of everyone in chat at the time).

His incoming packets stop entirely. But his outgoing packets are still active.

Here's the log of the activity:
[rtclog-1775248203555.log](https://github.com/user-attachments/files/26471450/rtclog-1775248203555.log)
